name: Run at 6:14 PM UTC

on:
  schedule:
    - cron: '20 11 * * *'
    
  push:
    branches:
    - main # Runs at 6:14 PM UTC every day

jobs:
  run_at_6_14:
    runs-on: ubuntu-latest
    steps:
      - name: Display the current time
        run: echo "The current time is $(date)"
